"""Add rating in Publication

Revision ID: 60dc7c833e14
Revises: db08a9a309c0
Create Date: 2024-02-06 20:13:38.465110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60dc7c833e14'
down_revision = 'db08a9a309c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('rating', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'rating')
    # ### end Alembic commands ###
